version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - TEMPORAL_SERVER_URL=temporal:7233
    depends_on:
      - temporal

  temporal:
    image: temporalio/auto-setup:1.20.0
    ports:
      - "7233:7233"